sudo: required
language: generic

services:
  - docker

before_install:
  - echo "before docker build:"
  - ls
  - docker build -t jm/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jm/docker-react npm run test -- --coverage
  - echo "before deploy:"
  - ls

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react2"
  env: "DockerReact2-env"
  bucket_name: "elasticbeanstalk-us-west-2-339276244151"
  bucket_path: "docker-react2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

script:
  - echo "after deploy:"
  - ls

